apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    run: es2
  name: es2
spec:
  replicas: 1
  selector:
    run: es2
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: es2
    spec:
      containers:
      - args:
        - elasticsearch
        - -Ebootstrap.seccomp=false
        - -E
        - discovery.zen.ping.unicast.hosts=es1
        - -E
        - discovery.zen.ping.unicast.hosts=es2
        - -E
        - discovery.zen.ping.unicast.hosts=es3
        - -Ediscovery.zen.minimum_master_nodes=2
        env:
        - name: ES_JAVA_OPTS
          value: -Xms1g -Xmx1g
        image: registry.dataos.io/library/elasticsearch:5
        imagePullPolicy: IfNotPresent
        name: es2
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
status: {}
